# ─────────────────────────────────────────────────────────────────────────────
# Stage 1 — deps
#   Install only production + dev dependencies using the package-lock for a
#   fully reproducible install. We keep this layer separate so it is cached
#   independently of the source code.
# ─────────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS deps

WORKDIR /app

# Copy manifests first to exploit layer caching
COPY package.json package-lock.json ./

# ci instead of install: honours the lock-file exactly, faster in CI
RUN npm ci

# ─────────────────────────────────────────────────────────────────────────────
# Stage 2 — builder
#   Compile the Next.js application.  Build-time env vars that are NEXT_PUBLIC_*
#   need to be present here; secrets that live only server-side can be injected
#   at runtime via docker run / compose.
# ─────────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

WORKDIR /app

# Receive build-time public vars (injected by the GitHub Actions workflow via
# --build-arg; all are optional — Next.js will silently ignore undefined vars)
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_SITE_NAME

ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME}

# Tell Next.js to produce a standalone output bundle (smaller image)
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

# ─────────────────────────────────────────────────────────────────────────────
# Stage 3 — runner  (final, minimal image)
#   Only the standalone Next.js output + public assets + static files are
#   copied here.  No node_modules, no source code.
# ─────────────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS runner

WORKDIR /app

# Security best-practice: run as a non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Default port — override with docker run -e PORT=...
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Standalone output (generated by Next.js when output: 'standalone' is set)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static    ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public          ./public

USER nextjs

EXPOSE 3000

# next.js standalone entry point
CMD ["node", "server.js"]
